### ISSUE TITLE
Server box alignment messed up for odd number of servers

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/cafe-flask#5]
If an odd number of servers is given (i.e., if a server is down or could not be retrieved), the first two server boxes display fine but the third will be centered. This creates a weird flow and should be corrected so that the boxes display in a grid no matter what.

**Comment by GordonsBeard** [comment]
I was originally going to throw them in a table, but I kept them with this loose flow so if you're using a mobile device, or something with a resolution less than 1000px wide, the 4 boxes will "stack" on top of each other and still be visible.

![image](https://cloud.githubusercontent.com/assets/4015791/5964983/64addf32-a7ad-11e4-9ac7-779abb30d77b.png)
A display that's less than 1000px

**Comment by LanaCoyote** [comment]
I mean it'll do that whether or not the current way of aligning them is "text-align:center;"

**Comment by GordonsBeard** [comment]
"text-align: center; margin-left: auto; margin-right: auto;" is my jam.
