### ISSUE TITLE
Pull the event's picture from Steam

### ISSUE THREAD

**Issue by GordonsBeard** [GordonsBeard/cafe-flask#6]
When pulling in event data from Steam, we should also work to pull in the image provided with the event. When the event is "Playing a Game", it will use the game's icon, and that would be great to have on the cafe's website.

For example, the next event is for Tabletop Simulator, but nowhere in the actual text of the event do I mention "Tabletop Simulator", as it's implied you can see the picture along side of the event.

![image](https://cloud.githubusercontent.com/assets/4015791/5964939/04080b08-a7ad-11e4-8c0f-5d22fc70562a.png)
From event details.

![image](https://cloud.githubusercontent.com/assets/4015791/5964943/12d44f52-a7ad-11e4-9c0b-b0dfa8c1d979.png)
From the upcoming events on the group's main page.

Either of these images would be good to include.

**Comment by LanaCoyote** [comment]
Added in #11
