### ISSUE TITLE
Move caching code to a new file

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/cafe-flask#8]
Both the servers and community checkers use similar caching code. We should create a new file called "caching.py" and define some simple functions to get cache info rather than going with duplicate code. 

This way any bugs in one side of the code can be easily fixed on both.

Also "caching.py" should be pronounced ka-ching dot pie

**Comment by GordonsBeard** [comment]
ka-ching because it's going to be MONEY
