### ISSUE TITLE
Don't specify exception types in caching try/except block?

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/cafe-flask#9]
In the current caching implementation (at least in community.py), I use a try/except block to update the cache data if an error occurs while reading it. Multiple exceptions can be thrown during the process of reading the cache data, including receiving invalid data and being unable to read the file.

At the moment I specify the kinds of exceptions to catch. I consider this to be good practice, so that if something bad happens (such as an exception unrelated to caching) it'll be raised normally. However, there's a number of things that can go wrong in the caching process, and some errors I can't account for. Should we continue specifying the exceptions to catch or should we use a general except clause that will refresh cache information regardless of error?

**Comment by GordonsBeard** [comment]
I always favor being specific with the exceptions only because there are only so many types of failures we should be expecting.

A general "catch all" at the end would be alright for debugging purposes or instrumentation - just to see how often our normal exception handling fails.
